### ISSUE TITLE
Reduce screen flickering

### ISSUE THREAD

**Issue by mikkun** [mikkun/AWKTC#1]
## Overview

After storing all screen data in a variable for buffer, it is necessary to display them on the terminal at once.

## Purpose

To reduce screen flickering.

## Task

- [x] Remove trailing semicolons
- [x] Simplify keyboard input processing
- [x] Replace `printf()` with `buffer = buffer sprintf()`
- [x] Rename user-defined functions
